<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/MetadataItem.proto

namespace GPBMetadata\Events;

class MetadataItem
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a194576656e74732f4d657461646174614974656d2e70726f746f22" .
            "2a0a0c4d657461646174614974656d120b0a034b6579180120012809120d" .
            "0a0556616c7565180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

